site:
  title: Dusty Portfolio Terminal
  legacy_url: https://gray-glacier-0dd347e0f.azurestaticapps.net
  contact_email: dusty@dustywright.me

github:
  username: rdw100
  projects:
    - anthrocloud
    - benchmark
    - clean
    - northwind-web-api
    - orm-dapper
    - StockApp
    - terminal-portfolio
    
socials:
  linkedin: https://www.linkedin.com/in/rdw100
  github: https://github.com/rdw100
  gui: https://gray-glacier-0dd347e0f.azurestaticapps.net