name: Azure Static Web Apps â€“ Manual Cache Purge

on:
  workflow_dispatch:

jobs:
  purge:
    runs-on: ubuntu-latest
    steps:
      - name: Purge Azure Static Web App Cache
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PURPLE_SAND_0AC49090F }}
          action: "purge"
          app_location: "/"